console.log("yo");
const CENTER = [24.146, 89.074];
const KOLKATA = [22.5726, 88.3639];
const KOLKATA_DUTT = [22.5477, 88.3621];
const SAGARDARI = [22.8193, 89.1617];
const DHAKA = [23.8103, 90.4125];
const CHINSURAH = [22.9012, 88.3899];
const SANTINIKETAN = [23.6776, 87.6852];
const BARISAL = [22.7010, 90.3535];
const KOLKATA_BARISAL_MIDPOINT = [(KOLKATA[0] + BARISAL[0]) / 2, (KOLKATA[1] + BARISAL[1]) / 2];
const DEFAULTZOOM = 6;
const DHAKA_MEDICAL_COLLEGE = [23.7260, 90.3976];
const MODERN_SHAHEED_MINAR_COORDS = [23.7272, 90.3966];

const VANDE_MATARAM = {coords: CHINSURAH, title: "Vande Mataram", author: "Bankim Chandra Chatterjee", year: "1882", text: `Mother, I bow to thee!<br>Rich with thy hurrying streams,<br>Bright with thy orchard gleams,<br>Cool with the winds of delight,<br>Dark fields waving, Mother of might,<br>Mother free.<br><br>Glory of moonlight dreams,<br>Over thy branches and lordly streams,<br>Clad in thy blossoming trees,<br>Mother, giver of ease,<br>Laughing low and sweet,<br>Mother, I kiss thy feet,<br>Speaker sweet and low,<br>Mother, to thee I bow.<br><br>Who hath said thou art weak in thy lands,<br>When the swords flash out in seventy million hands,<br>And seventy million voices roar<br>Thy dreadful name from shore to shore?<br>With many strengths who art mighty and strong,<br>To thee I call, Mother and Lord!<br>Thou who savest, arise and save!<br>To her I cry who ever her foemen drove<br>Back from plain and Sea<br>And shook herself free.<br><br>Thou art wisdom, thou art law,<br>Thou art heart, our soul, our breath<br>Thou art love divine, the awe<br>In our hearts that conquers death.<br>Thine the strength that nerves the arm,<br>Thine the beauty, thine the charm.<br>Every image divine.<br>In our temples is but thine.<br><br>Thou art Goddess Durga, Lady and Queen,<br>With her hands that strike and her swords of sheen,<br>Thou art Goddess Kamala (Lakshmi), lotus-throned,<br>And Goddess Vani (Saraswati), bestower of wisdom known<br>Pure and perfect without peer,<br>Mother lend thine ear,<br>Rich with thy hurrying streams,<br>Bright with thy orchard gleams,<br>Dark of hue O candid-fair<br><br>In thy soul, with jewelled hair<br>And thy glorious smile divine,<br>Loveliest of all earthly lands,<br>Showering wealth from well-stored hands!<br>Mother, mother mine!<br>Mother sweet, I bow to thee,<br>Mother great and free!<br><br><a href="https://en.wikipedia.org/wiki/Vande_Mataram#Translation">(translation source)</a>`}
const DUTT_EPITAPH = {coords: KOLKATA_DUTT, title: "self-written epitaph", author: "Michael Madhusudan Dutt", year: "~1873", text:`Stop a while, traveller!<br>Should Mother Bengal claim thee for her son.<br>As a child takes repose on his mother's elysian lap,<br>Even so here in the Long Home,<br>On the bosom of the earth,<br>Enjoys the sweet eternal sleep<br>Poet Madhusudan of the Duttas.<br><a href="https://en.wikipedia.org/wiki/Michael_Madhusudan_Dutt#Legacy_and_honours">(translation source)</a>`}
const KAPATAKKHA_RIVER = {coords: SAGARDARI, title: "Kapatakkha River", author: "Michael Madhusan Dutt", year: "~1866", text:`Always, o river, you peep in my mind.<br>Always I think you in this loneliness.<br>Always I soothe my ears with the murmur<br>Of your waters in illusion, the way<br>Men hear songs of illusion in a dream.<br>Many a river I have seen on earth;<br>But which can quench my thirst the way you do?<br>You're the flow of milk in my homeland's breasts.<br>Will I meet you ever? As long as you<br>Go to kinglike ocean to pay the tax<br>Of water, I beg to you, sing my name<br>Into the ears of people of Bengal,<br>Sing his name, o dear, who in this far land<br>Sings your name in all his songs for Bengal.<br><a href="https://en.wikipedia.org/wiki/Michael_Madhusudan_Dutt#Work_with_the_sonnet">(translation source)</a>`}
const AMAR_SONAR_BANGLA = {coords: SANTINIKETAN, title: "Amar Sonar Bangla", author: "Rabindranath Tagore", year:"1905", text:`My golden Bengal, I love you.<br>Forever thy skies, thy air set my heart in tune as if it were a flute,<br>O mother! The aroma of the mango orchard in Falgun drives me crazy,<br>Ah, what a thrill!<br>O mother! In Ogrohayon time sees sweet smiles all through mature fields of paddy.<br>What beauty, what shades, what affection, what tenderness!<br>What a quilt have thee spread at the feet of banyan trees and along the bank of every river,<br>Oh mother mine, words from thy lips are like nectar to my ears.<br>Ah, what a thrill!<br>If sadness, O mother! casts a gloom on your face, my eyes are filled with tears!<br>Spending my childhood in your playhouse<br>Your dirt and soil smeared all over my body, I consider myself privileged.<br>The wonderful lamp you light up at dusk,<br>Ah, what a thrill!<br>I quit play and sprint back to your lap at once, O mother!<br>In the cattle grazing field, on the pier for crossing stream,<br>Shaded village walkways, serene with calling birds,<br>Open porch with heaped ripe paddy my life goes on.<br>Ah, what a thrill!<br>All your shepherds and farmers are my brothers.<br>This time I offer my head beneath your feet,<br>Bless me with your dust, I shall be obliged to flaunt overhead.<br>I shall offer you meagrely whatever I have at home,<br>Ah, what a thrill!<br>Never bother to buy you, from others, a hanging rope disguised as a crown.<br><a href="https://en.wikipedia.org/wiki/Amar_Sonar_Bangla#Lyrics">(translation source)</a>`};
const JANA_GANA_MANA = {coords: SANTINIKETAN, title: "Bharoto Bhagyo Bidhata", author: "Rabindranath Tagore", year:"1911", text:`Oh! the ruler of the minds of people, victory be to You, dispenser of the destiny of India!<br>Punjab, Sindh, Gujarat, Maratha (Marathi heartland), Dravida (South India), Orissa and Bengal,<br>The Vindhyas, the Himalayas, the Jumna (Yamuna) and the Ganges, and the oceans with foaming waves all around.<br>Wake up listening to Your auspicious name, ask for Your auspicious blessings,<br>And sing to Your glorious victory.<br>Oh! You who impart well being to the people, victory be to You, dispenser of the destiny of India!<br>Victory, victory, victory to You!<br><br>Your call is announced continuously, we heed Your gracious call<br>The Hindus, Buddhists, Sikhs, Jains, Parsis, Muslims and Christians,<br>The East and the West come together, to the side of Your throne<br>And weave the garland of love.<br>Oh! You who bring in the unity of the people! Victory be to You, dispenser of the destiny of India!<br>Victory, victory, victory to You!<br><br>The way of life is somber as it moves through ups and downs, but we, the pilgrims, have followed it through ages.<br>Oh! Eternal Charioteer, the wheels of your chariot echo day and night in the path<br>In the midst of fierce revolution, your conch shell sounds.<br>You save us from fear and misery.<br>Oh! You who guide the people through torturous path, victory be to You, dispenser of the destiny of India!<br>Victory, victory, victory to You!<br><br>During the bleakest of nights, when the whole country was sick and in swoon<br>Wakeful remained Your incessant blessings, through Your lowered but wink-less eyes<br>Through nightmares and fears, you protected us on Your lap,<br>Oh Loving Mother<br>Oh! You who have removed the misery of the people, victory be to You, dispenser of the destiny of India!<br>Victory, victory, victory to You!<br><br>The night is over, and the Sun has risen over the hills of the eastern horizon.<br>The birds are singing, and a gentle auspicious breeze is pouring the elixir of new life.<br>By the halo of Your compassion, India that was asleep is now waking<br>On your feet we now lay our heads<br>Oh! Victory, victory, victory to you, the Supreme King, victory be to You, dispenser of the destiny of India!<br>Victory, victory, victory to You!<br><a href="https://en.wikipedia.org/wiki/Bharoto_Bhagyo_Bidhata#Lyrics_of_all_5_stanzas">(translation source)</a>`};
const BIDROHI = {coords: KOLKATA, title: "Bidrohi (excerpt)", author: "Kazi Nazrul Islam", year:"1921", text: `I am the unutterable grief,<br>I am the trembling first touch of the virgin,<br>I am the throbbing tenderness of her first stolen kiss.<br>I am the fleeting glance of the veiled beloved,<br>I am her constant surreptitious gaze...<br><br>I am the burning volcano in the bosom of the earth,<br>I am the wildfire of the woods,<br>I am Hell's mad terrific sea of wrath!<br>I ride on the wings of lightning with joy and profundity,<br>I scatter misery and fear all around,<br>I bring earthquakes on this world!<br><br>I am the rebel eternal,<br>I raise my head beyond this world,<br>High, ever erect and alone!<br><a href="https://web.archive.org/web/20071026083724/http://www.nazrul.org/nazrul_works/poems_lyrics/kabir_rebel.htm">(translation by Kabir Chaudhury)</a>`}
const DARIDRO = {coords: KOLKATA, title: "Daridro (excerpt)", author: "Kazi Nazrul Islam", year: "1926", text: `O poverty, thou hast made me great<br>Thou hast made me honoured like Christ<br>With his crown of thorns. Thou hast given me<br>Courage to reveal all. To thee I owe<br>My insolent, naked eyes and sharp tongue.<br>Thy curse has turned my violin to a sword...<br>O proud saint, thy terrible fire<br>Has rendered my heaven barren.<br>O my child, my darling one<br>I could not give thee even a drop of milk<br>No right have I to rejoice.<br>Poverty weeps within my doors forever<br>As my spouse and my child.<br>Who will play the flute?<br><a href="https://web.archive.org/web/20070610003225/http://www1.worldbank.org/prem/poverty/povlit/povlit2p29.htm">(translation by Kabir Chaudhury)</a>`}
const CAPTAIN = {coords: KOLKATA, title: "Durgom Giri Kantar Moru (excerpt)", author: "Kazi Nazrul Islam", year: "~1928", text: "Who asks, \"Hindu or Muslim\"?<br>All the children of the motherland are drowning. (translation mine)"};
const DAS_1946_47 = {coords: KOLKATA_BARISAL_MIDPOINT, title: "1946-47", author: "Jibanananda Das", year: "~1948", text: `<a href="https://allpoetry.com/1946-47">link to poem (translated into English)</a>`}
const FIRST_SHAHEED_MINAR = {coords: DHAKA_MEDICAL_COLLEGE, title: "First Shaheed Minar (Martyr's Memorial)", author: "students of Dhaka Medical College", year:"1952", text:`<img src="https://upload.wikimedia.org/wikipedia/commons/7/70/First_Shaheed_Minar_1952.jpg\" alt="First Shaheed Minar"><br><p>On February 23, 1952, students constructed this memorial to the students killed by police during the Bengali Language Movement demonstrations on February 21. It was demolished by Pakistani police forces on February 26th, 1952.</p>`}
const SECOND_SHAHEED_MINAR = {coords: DHAKA_MEDICAL_COLLEGE, title: "Second and Third Shaheed Minar (Martyr's Memorial)", author: "students of Dhaka Medical College, and a committee of the United Front government", year:"1954 and 1963", text:`<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Shaheed_Minar_at_Dhaka_Madical_College_21_Feb_1954.png/264px-Shaheed_Minar_at_Dhaka_Madical_College_21_Feb_1954.png" alt="Second Shaheed Minar"><br><p>In 1954, demonstrators supported by the radical pro-independence United Front government built a second martyr's memorial at the same location as the previous one, which had been destroyed by Pakistani police forces. The United Front government commissioned the construction of a larger memorial that was completed in 1963. It was destroyed by Pakistani military forces during Operation Searchlight in 1971.</p>`}
const MODERN_SHAHEED_MINAR = {coords: MODERN_SHAHEED_MINAR_COORDS, title: "Modern Shaheed Minar (Martyr's Memorial)", author: "Bangladeshi government committee", year:"1972", text:`<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Shaheed_Minar.JPG/320px-Shaheed_Minar.JPG" alt="First Shaheed Minar"><br><p>After the second Shaheed Minar (Martyr's Memorial) was destroyed by Pakistani military forces during Operation Searchlight in 1971, Bangladesh won its independence from Pakistan through the 1971 Bangladesh Liberation War. In 1972, the new government established a committee to rebuild the monument. That version stands to this day.</p>`}
const SHAME_ON_YOU_CALCUTTA = {coords: KOLKATA, title: "Shame on You Calcutta", author: "Malay Roy Choudhury", year: "~1960", text: `Stay and live with your eunuchs<br>You are their nurse who piss in bed in winter rain<br>Lift their legs and change wet pants<br>Write great words on walls to be urinated by pimps<br>I don't want to meddle in your affairs now. Lips will turn sour if I kiss you<br>after death.<br>Go and join the revolt of clerks in BBD Baug<br>You call us to dropp our coin in your Bank of Skulls<br>But I am a monster inferior to man<br>Can smother you with my elastic limbs<br>Tie boulders on your legs and through you in the sea.<br>When I enter, the pimps keep knocking at your door<br>'Hurry up, a customer is waiting for a go'.<br><a href="https://www.poetrynook.com/poem/shame-you-calcutta">(translation source)</a>`}
const STARK_ELECTRIC_JESUS = {coords: KOLKATA, title: "Stark Electric Jesus (excerpt)", author: "Malay Roy Choudhury", year: "1963", text: `<a href="https://www.poetrynook.com/poem/stark-electric-jesus">(link to full poem)</a><br><br>I'd have gone two billion light years and kissed God's ass<br>But nothing pleases me nothing sounds well<br>I feel nauseated with more than a single kiss<br>I've forgotten women during copulation and returned to the Muse<br>In to the sun-coloured bladder<br>I do not know what these happenings are but they are occurring within me<br>I'll destroy and shatter everything<br>draw and elevate Shubha in to my hunger<br>Shubha will have to be given<br><a href="https://www.poetrynook.com/poem/stark-electric-jesus">(translation source)</a>`};
const FREEDOM_YOU_ARE = {coords: DHAKA, title: "Shadhinota tumi (Liberation)",  author: "Shamsur Rahman", year: "1971", text: `Freedom, you're<br>Rabi Thakur's timeless poetry and everlasting lyrics.<br><br>Freedom, you're<br>Kazi Nazrul, his willowy mane swaying,<br>rapturous with the joy of creation, a great man.<br>Freedom, you're<br>the radiant gathering at Shahid Minar on the<br>immortalized February 21.<br>Freedom, you're<br>the flag-draped, slogan-serenaded boisterous<br>procession.<br>Freedom, you're<br>the farmer's beam amidst his fields.<br>Freedom, you're<br>the lightsome swim of a village lass in a pond in<br>mid-day sun.<br>Freedom, you're<br>the sinewy muscle on a young laborer's sun-bronzed,<br>skilled arms.<br>Freedom, you're<br>the gleam in a freedom-fighter's eyes, scanning the<br>horizon draped in darkness.<br>Freedom, you're<br>the crisply-worded, spirited speech of a bright, young<br>learner in the shade of a banyan tree.<br>Freedom, you're<br>the tumult of chats in tea-shops, parks and fields.<br>Freedom, you're<br>the roaring swoop of kal-boishakhi across the horizon.<br>Freedom, you're<br>the heart of river Meghna, shoreless in Sraban.<br>Freedom, you're<br>the soft stretch of father's chivalrous prayer-mat.<br>Freedom, you're<br>the ripples on mother's bright sari spread out on the<br>yard.<br>Freedom, you're<br>the hue of henna on sister's gentle hands.<br>Freedom, you're<br>the colorful poster, tremulous as starlight in the<br>hands of a friend.<br><br>Freedom, you're<br>the homemaker's raven hair, luxurious and undone,<br>untamed and wild in the wind.<br>Freedom, you're:<br>the colorful jacket on a lad.<br>the playful sunlight bouncing off a young girl's supple<br>cheeks.<br>Freedom, you're:<br>The home amidst a flower garden; the warble of<br>koel-bird.<br>The twittering leaves of antediluvian banyan trees.<br>My notebook of poetry, to pen poems as I please.<br><a href="https://eportfolios.macaulay.cuny.edu/blot13/2013/11/04/a-poem-on-freedom/">(translation source)</a>`}
const ROARING_LIBERATION = {coords: DHAKA, title: "Roaring Liberation", year: "1972", author: "Shamsur Rahman", text: `What would I do with the spring when mournfully cries the cuckoo, when flowers are not in bloom?<br>What would I do with the garden where birds never visit, where the soil is unwieldy and the skeleton-like trees are ghostly presences?<br>What would I do with the love forcing upon me a thorny-crown and offering a cup of poison?<br>What use is the path where no one walks, where the colourful ice-cream-seller goes missing and where the incessant waves of urban marches is absent?<br><br>My beloved, when we were marching towards the sun-rise,I had called you,<br>the discreet charms of bourgeois life had enveloped you then - were you not keen to realise the power of the songs sung en masse?<br>You are a prisoner of anguish now, you do not see the carpeted rainbow anymore. <br>     Walking the distance without you is difficult now,<br><br>as that dreadful monster demolishes the foundation of a new civilisation, and the sky gets darkened,<br>And the full moon is hung, an announcement forbids the blossoming of the lotus and the rose <br>as well as stifles the magpie-robin's song, <br>to render unutterable my poetic illustration of your breath and the fragrance of your hair.<br><br>The hope for good days if delayed can turn a youthful body decrepit, <br>This excuse for aging <br>Is an excuse for Nelson Mandela's enduring imprisonment<br>Is also an excuse for Nur Hossain's heroic sacrifice,<br>As the freedom bell tolls like an anguished Titan, and <br>                          the hands in chain are freed of their manacles, there is tremor <br>in the distance, we hear our Liberation is roaring.  <br><a href="https://www.thedailystar.net/supplements/independence-day-2016/roaring-liberation-1199581">(translation by Asif Iqbal)</a>`}
const THE_RAIN = {coords: KOLKATA, title: "The Rain on Calcutta's Breast", author: "Shakti Chattopadhay", year: "1978", text: `We hadn't asked for it, still the rain, like galloping hooves<br>Ran out on the tin shed, flowers were sprinkled on the road<br>A stain trickled down the garbage hillock, a different<br>Black torrent facing ugly houses instead of bungalows<br>Of Calcutta, the rain came, the rain flooded the bylanes<br>Swept away stories, rags, fish scales and peel, everything<br>The humidity in middle-class homes, insurance poliices on<br>Strewn strips of paper, voting ballots, dry wood shavings -<br>All of these. From the rain to the picnic in the rain, all of it<br>Is useful for Calcutta, dead grass - that's useful too<br>The labour room on one side, crematorium ashes on the other<br>Birth and death, all the details, are neatly arrayed in the rain<br>In a satin case inevitable lumps of cottonwool rest<br>The rain goes to bed a little late on Calcutta's breast<br>(translation by Arunava Sinha in <i>Desire for Fire: Modern Bengali Poetry</i>)>(translation source)</a>`}
const GIVE_ME_FOOD_BASTARD = {coords: DHAKA, title: "Give Me Food, Bastard", author: "Rafiq Azad", year: "1974", text: `I am terribly hungry:<br>	in the depth of my belly,<br>	throughout the length and breath of my body<br>I feel, every moment,<br>	fierce pangs of an all-devouring hunger<br>Like summer corn-fields seared by drought<br>my body is ablaze with the fire of hunger.<br><br>I am content if I get two square meals a day.<br>I have absolutely no other demand.<br>Many persons ask for many things.<br>Everyone wants a house, a car, money;<br>some hunger for fame.<br>But my wants are few.<br><br>What I ask for is little. I want food. I feel a burning fire in the pit of my stomach.<br>What I want is plain and simple:<br>I want rice. I don't care if it is cold or hot,<br>Or if the grains are fine or red and coarse<br>	like the rice doled out by ration shops.<br><br>I don't care as long as I get<br>	my plate-full of rice.<br>If I get two square meals a day,<br>	I tell you,<br>	I'll give up all other demands of time.<br>No unfair demands have I,<br>I don't have even sex-hunger.<br>I don't want a sari<br>	draped around an inviting body<br>	showing an exposed navel<br>Or even the owner of that sari.<br>Let whoever wants it, take her.<br>Give her away to whoever you like..<br>I have no need, I tell you, of any of those things.<br><br>But if you can't satisfy this demand of mine,<br>things will go very wrong in your kingdom.<br>The hungry one does not know<br>	what is right or wrong,<br>	what is good or bad,<br>he does not know laws, rules, or statutes.<br>I'll unheistatingly devour<br>	all that I'll find in front of me.<br>I tell you, nothing will be spared.<br>Everything will rush into my jaws.<br>And perchance if I find you before me<br>you will surely be transformed into a tasty morsel<br>	before my giant hunger.<br>This simple hunger for food,<br>	if allowed to grow and encompass everything,<br>can surely bring about a disastrous end.<br>Devouring everything<br>	fro sight to the seer<br>I shall at last eat up one by one<br>shrubs and trees, lakes and rivers, villages and cities,<br>sidewalks, the flowing waters of the drain,<br>streams of people walking on the streets,<br>women all bottom and hips,<br>the Food Minister and his flag-flying limousine -<br>nothing, absolutely nothing today<br>will be unacceptable to me.<br>Give me food, you bastard,<br>	or I'll eat up the very map.<br>(Translated by Kabir Chowdhury in <i>100 Poems From Bangladesh</i><br>)`};
const SIN = {coords: KOLKATA, title: "Sin", author: "Mallika Sengupta", year: "~1985", text: `Adam and Eve were full of love; unenlightened<br>they were never feminist or male chauvinist.<br><br>Who was the priest who set the word 'sin' in between men and women!<br>He was the disguised snake; he who hid twice in the apple cores<br><br>was seen to in the sacrifice of Janamejaya and<br>in the heavenly garden, he was the black cuckoo, laying eggs<br>in others' nests and flying away to the horizeon; in the Bible<br><br>meanwhile appears the worship of the phallus -- on the 14th of Phalgun<br>consuming the opium of religion all women fell asleep<br>on the Manikarnika landing; the Vatican's conspiracy began.<br>(Translated by Marian Maddern in <i>When Poetry Comes: A selection of poems by contemporary Bengali women poets in English translation</i>)`}
//const MY_MARKERS = [{coords: KOLKATA, title: "Poem", author: "Author Authorson", year: "1950"}, {coords: KOLKATA, title: "Poem 2", author: "Author Authorson II", year: "2000"}, {coords: [23.75973, 90.41213], title: "Poem 3", author: "Author Authorson III", year: "2022"}];
const DATASET = [KAPATAKKHA_RIVER, VANDE_MATARAM, DUTT_EPITAPH, AMAR_SONAR_BANGLA, JANA_GANA_MANA, BIDROHI, DARIDRO, CAPTAIN, DAS_1946_47, FIRST_SHAHEED_MINAR, SECOND_SHAHEED_MINAR, MODERN_SHAHEED_MINAR, SHAME_ON_YOU_CALCUTTA, STARK_ELECTRIC_JESUS, FREEDOM_YOU_ARE, ROARING_LIBERATION, THE_RAIN, GIVE_ME_FOOD_BASTARD, SIN];

 function addData(layer, url) {
    var xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.responseType = 'json';
    xhr.onload = function() {
        if (xhr.status !== 200) return
        layer.addData(xhr.response)
    };
    xhr.send();
    return layer;
 }