const CENTER = [24.146, 89.074];
const KOLKATA = [22.5726, 88.3639];
const KOLKATA_DUTT = [22.5477, 88.3621];
const SAGARDARI = [22.8193, 89.1617];
const DHAKA = [23.8103, 90.4125];
const CHINSURAH = [22.9012, 88.3899];
const SANTINIKETAN = [23.6776, 87.6852];
const DEFAULTZOOM = 6;

const VANDE_MATARAM = {coords: CHINSURAH, title: "Vande Mataram", author: "Bankim Chandra Chatterjee", year: "1882", text: "Mother, I bow to thee!<br>Rich with thy hurrying streams,<br>Bright with thy orchard gleams,<br>Cool with the winds of delight,<br>Dark fields waving, Mother of might,<br>Mother free.<br><br>Glory of moonlight dreams,<br>Over thy branches and lordly streams,<br>Clad in thy blossoming trees,<br>Mother, giver of ease,<br>Laughing low and sweet,<br>Mother, I kiss thy feet,<br>Speaker sweet and low,<br>Mother, to thee I bow.<br><br>Who hath said thou art weak in thy lands,<br>When the swords flash out in seventy million hands,<br>And seventy million voices roar<br>Thy dreadful name from shore to shore?<br>With many strengths who art mighty and strong,<br>To thee I call, Mother and Lord!<br>Thou who savest, arise and save!<br>To her I cry who ever her foemen drove<br>Back from plain and Sea<br>And shook herself free.<br><br>Thou art wisdom, thou art law,<br>Thou art heart, our soul, our breath<br>Thou art love divine, the awe<br>In our hearts that conquers death.<br>Thine the strength that nerves the arm,<br>Thine the beauty, thine the charm.<br>Every image divine.<br>In our temples is but thine.<br><br>Thou art Goddess Durga, Lady and Queen,<br>With her hands that strike and her swords of sheen,<br>Thou art Goddess Kamala (Lakshmi), lotus-throned,<br>And Goddess Vani (Saraswati), bestower of wisdom known<br>Pure and perfect without peer,<br>Mother lend thine ear,<br>Rich with thy hurrying streams,<br>Bright with thy orchard gleams,<br>Dark of hue O candid-fair<br><br>In thy soul, with jewelled hair<br>And thy glorious smile divine,<br>Loveliest of all earthly lands,<br>Showering wealth from well-stored hands!<br>Mother, mother mine!<br>Mother sweet, I bow to thee,<br>Mother great and free!<br>"}
const DUTT_EPITAPH = {coords: KOLKATA_DUTT, title: "self-written epitaph", author: "Michael Madhusudan Dutt", year: "~1873", text:"Stop a while, traveller!<br>Should Mother Bengal claim thee for her son.<br>As a child takes repose on his mother's elysian lap,<br>Even so here in the Long Home,<br>On the bosom of the earth,<br>Enjoys the sweet eternal sleep<br>Poet Madhusudan of the Duttas.<br>"}
const KAPATAKKHA_RIVER = {coords: SAGARDARI, title: "Kapatakkha River", author: "Michael Madhusan Dutt", year: "~1866", text:"Always, o river, you peep in my mind.<br>Always I think you in this loneliness.<br>Always I soothe my ears with the murmur<br>Of your waters in illusion, the way<br>Men hear songs of illusion in a dream.<br>Many a river I have seen on earth;<br>But which can quench my thirst the way you do?<br>You're the flow of milk in my homeland's breasts.<br>Will I meet you ever? As long as you<br>Go to kinglike ocean to pay the tax<br>Of water, I beg to you, sing my name<br>Into the ears of people of Bengal,<br>Sing his name, o dear, who in this far land<br>Sings your name in all his songs for Bengal.<br>"}
const AMAR_SONAR_BANGLA = {coords: SANTINIKETAN, title: "Amar Sonar Bangla", author: "Rabindranath Tagore", year:"1905", text:"My golden Bengal, I love you.<br>Forever thy skies, thy air set my heart in tune as if it were a flute,<br>O mother! The aroma of the mango orchard in Falgun drives me crazy,<br>Ah, what a thrill!<br>O mother! In Ogrohayon time sees sweet smiles all through mature fields of paddy.<br>What beauty, what shades, what affection, what tenderness!<br>What a quilt have thee spread at the feet of banyan trees and along the bank of every river,<br>Oh mother mine, words from thy lips are like nectar to my ears.<br>Ah, what a thrill!<br>If sadness, O mother! casts a gloom on your face, my eyes are filled with tears!<br>Spending my childhood in your playhouse<br>Your dirt and soil smeared all over my body, I consider myself privileged.<br>The wonderful lamp you light up at dusk,<br>Ah, what a thrill!<br>I quit play and sprint back to your lap at once, O mother!<br>In the cattle grazing field, on the pier for crossing stream,<br>Shaded village walkways, serene with calling birds,<br>Open porch with heaped ripe paddy my life goes on.<br>Ah, what a thrill!<br>All your shepherds and farmers are my brothers.<br>This time I offer my head beneath your feet,<br>Bless me with your dust, I shall be obliged to flaunt overhead.<br>I shall offer you meagrely whatever I have at home,<br>Ah, what a thrill!<br>Never bother to buy you, from others, a hanging rope disguised as a crown.<br>"};
const JANA_GANA_MANA = {coords: SANTINIKETAN, title: "Bharoto Bhagyo Bidhata", author: "Rabindranath Tagore", year:"1911", text:"Oh! the ruler of the minds of people, victory be to You, dispenser of the destiny of India!<br>Punjab, Sindh, Gujarat, Maratha (Marathi heartland), Dravida (South India), Orissa and Bengal,<br>The Vindhyas, the Himalayas, the Jumna (Yamuna) and the Ganges, and the oceans with foaming waves all around.<br>Wake up listening to Your auspicious name, ask for Your auspicious blessings,<br>And sing to Your glorious victory.<br>Oh! You who impart well being to the people, victory be to You, dispenser of the destiny of India!<br>Victory, victory, victory to You!<br><br>Your call is announced continuously, we heed Your gracious call<br>The Hindus, Buddhists, Sikhs, Jains, Parsis, Muslims and Christians,<br>The East and the West come together, to the side of Your throne<br>And weave the garland of love.<br>Oh! You who bring in the unity of the people! Victory be to You, dispenser of the destiny of India!<br>Victory, victory, victory to You!<br><br>The way of life is somber as it moves through ups and downs, but we, the pilgrims, have followed it through ages.<br>Oh! Eternal Charioteer, the wheels of your chariot echo day and night in the path<br>In the midst of fierce revolution, your conch shell sounds.<br>You save us from fear and misery.<br>Oh! You who guide the people through torturous path, victory be to You, dispenser of the destiny of India!<br>Victory, victory, victory to You!<br><br>During the bleakest of nights, when the whole country was sick and in swoon<br>Wakeful remained Your incessant blessings, through Your lowered but wink-less eyes<br>Through nightmares and fears, you protected us on Your lap,<br>Oh Loving Mother<br>Oh! You who have removed the misery of the people, victory be to You, dispenser of the destiny of India!<br>Victory, victory, victory to You!<br><br>The night is over, and the Sun has risen over the hills of the eastern horizon.<br>The birds are singing, and a gentle auspicious breeze is pouring the elixir of new life.<br>By the halo of Your compassion, India that was asleep is now waking<br>On your feet we now lay our heads<br>Oh! Victory, victory, victory to you, the Supreme King, victory be to You, dispenser of the destiny of India!<br>Victory, victory, victory to You!<br>"};
const BIDROHI = {coords: KOLKATA, title: "Bidrohi (excerpt)", author: "Kazi Nazrul Islam", year:"1921", text: "I am the unutterable grief,<br>I am the trembling first touch of the virgin,<br>I am the throbbing tenderness of her first stolen kiss.<br>I am the fleeting glance of the veiled beloved,<br>I am her constant surreptitious gaze...<br><br>I am the burning volcano in the bosom of the earth,<br>I am the wildfire of the woods,<br>I am Hell's mad terrific sea of wrath!<br>I ride on the wings of lightning with joy and profundity,<br>I scatter misery and fear all around,<br>I bring earthquakes on this world!<br><br>I am the rebel eternal,<br>I raise my head beyond this world,<br>High, ever erect and alone!<br>"}
const DARIDRO = {coords: KOLKATA, title: "Daridro (excerpt)", author: "Kazi Nazrul Islam", year: "1926", text: "O poverty, thou hast made me great<br>Thou hast made me honoured like Christ<br>With his crown of thorns. Thou hast given me<br>Courage to reveal all. To thee I owe<br>My insolent, naked eyes and sharp tongue.<br>Thy curse has turned my violin to a sword...<br>O proud saint, thy terrible fire<br>Has rendered my heaven barren.<br>O my child, my darling one<br>I could not give thee even a drop of milk<br>No right have I to rejoice.<br>Poverty weeps within my doors forever<br>As my spouse and my child.<br>Who will play the flute?<br>"}
const CAPTAIN = {coords: KOLKATA, title: "Durgom Giri Kantar Moru (excerpt)", author: "Kazi Nazrul Islam", year: "~1928", text: "Who asks, \"Hindu or Muslim\"?<br>All the children of the motherland are drowning."}
//const MY_MARKERS = [{coords: KOLKATA, title: "Poem", author: "Author Authorson", year: "1950"}, {coords: KOLKATA, title: "Poem 2", author: "Author Authorson II", year: "2000"}, {coords: [23.75973, 90.41213], title: "Poem 3", author: "Author Authorson III", year: "2022"}];
const DATASET = [KAPATAKKHA_RIVER, VANDE_MATARAM, DUTT_EPITAPH, AMAR_SONAR_BANGLA, JANA_GANA_MANA, BIDROHI, DARIDRO, CAPTAIN];

 function addData(layer, url) {
    var xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.responseType = 'json';
    xhr.onload = function() {
        if (xhr.status !== 200) return
        layer.addData(xhr.response)
    };
    xhr.send();
    return layer;
 }